### ISSUE TITLE
NoMethod Error from Faraday http basic

### ISSUE THREAD

**Issue by ramhoj** [kanet77/togglv8#32]
Faraday has changed their API regarding HTTP basic:

We're using:  `faraday.basic_auth username, password`
The new API is: `faraday.request :authorization, :basic, username, password`

**Comment by kyrofa** [comment]
Still hitting this. If it can't be fixed, can the gemspec be updated to have proper dependency pinning? (faraday < 2)

**Comment by qelphybox** [comment]
Still hitting too.
```
web_1  | 2022-05-01 18:01:12 - NoMethodError - undefined method `basic_auth' for #<Faraday::Connection:0x00007fa47b322310 @parallel_manager=nil, @headers={"Content-Type"=>"application/json"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions verify=true>, @default_parallel_manager=nil, @manual_proxy=false, @builder=#<Faraday::RackBuilder:0x00007fa47b320178 @adapter=Faraday::Adapter::NetHttp, @handlers=[Faraday::Request::UrlEncoded]>, @url_prefix=#<URI::HTTPS https://www.toggl.com/api/v8/>, @proxy=nil>
web_1  | 
web_1  |         faraday.basic_auth username, password
web_1  |                ^^^^^^^^^^^:
web_1  |        /app/vendor/bundle/ruby/3.1.0/gems/togglv8-1.2.1/lib/togglv8/connection.rb:24:in `block in open'
web_1  |        /app/vendor/bundle/ruby/3.1.0/gems/faraday-2.2.0/lib/faraday/connection.rb:91:in `initialize'
web_1  |        /app/vendor/bundle/ruby/3.1.0/gems/faraday-2.2.0/lib/faraday.rb:98:in `new'
web_1  |        /app/vendor/bundle/ruby/3.1.0/gems/faraday-2.2.0/lib/faraday.rb:98:in `new'
web_1  |        /app/vendor/bundle/ruby/3.1.0/gems/togglv8-1.2.1/lib/togglv8/connection.rb:19:in `open'
web_1  |        /app/vendor/bundle/ruby/3.1.0/gems/togglv8-1.2.1/lib/togglv8/togglv8.rb:39:in `initialize'
```
